import { useBrowserForge } from "@/contexts/BrowserForgeContext";

export function CodeEditor() {
  const { config } = useBrowserForge();

  const argsGn = [
    `# ${config.name} — Chromium Build Configuration`,
    `# Auto-generated by BrowserForge Engineering Studio`,
    ``,
    `is_official_build = true`,
    `chrome_pgo_phase = 2`,
    `is_debug = false`,
    `target_cpu = "x64"`,
    ``,
    `# Brand`,
    `brand_name = "${config.name}"`,
    `brand_color = "${config.themeColor}"`,
    ``,
    `# Security Flags`,
    ...config.flags.map((f) => `${f.id} = ${f.enabled}`),
    ``,
    `# Compiler`,
    `is_clang = true`,
    `use_lld = true`,
    `symbol_level = 0`,
  ].join("\n");

  return (
    <div className="glass-card p-4 space-y-2">
      <h3 className="text-xs font-mono tracking-widest uppercase text-muted-foreground">
        args.gn <span className="text-primary/60">• live</span>
      </h3>
      <pre className="code-block text-[11px] leading-relaxed max-h-[260px]">{argsGn}</pre>
    </div>
  );
}
